cache:
  paths:
    - ~/.asdf/

asdf_plugin:
  stage: test
  before_script:
    - apk update && apk upgrade -U && apk add bash curl git
    - git clone --depth=1 https://github.com/asdf-vm/asdf.git ~/.asdf || cd ~/.asdf && git pull origin master && cd -
    - . ~/.asdf/asdf.sh
  script:
    - asdf plugin test lefthook "${CI_REPOSITORY_URL}" --asdf-plugin-gitref $CI_COMMIT_BRANCH  || exit 1
